import "./globals.css";

export const metadata = {
  title: "JobFinder",
  description: "Generated by create next app",
  icons: {
    icon: "/jobfinder.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <div id="portal-root"></div>
      </body>
    </html>
  );
}
